chore: prevent poetry 1.3 from removing setuptools
`poetry install` removes untracked packages by default in 1.3, among
them setuptools.  This causes all subsequent Python invocations
(including the one poetry uses to get the system tags from a virtual
environment) to fail with e.g.

``` Error processing line 1 of /opt/homebrew/Caskroom/miniforge/base/envs/test/lib/python3.10/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File
    "/opt/homebrew/Caskroom/miniforge/base/envs/test/lib/python3.10/site.py",
    line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'
```

As a workaround, make setuptools an explicit dev dependency so
`poetry install` works by default.  This is similar, but possibly
not identical, to https://github.com/python-poetry/poetry/issues/4242